using System;
using System.Windows.Forms;
using System.Drawing;
using System.Linq;
using System.Collections.Generic;

namespace Planet_Conquest
{
    public partial class Form2 : Form
    {
        // Variables to hold the info from form2 GUI 
        public string Username1 { get; set; }
        public string Username2 { get; set; }

        public int StartingResources { get; set; }

        public Color player1color, player2color;

        // Check that usernames aren't identical and that the team colors aren't identical
        private bool validName = false;
        private bool validColor = false;

        public Form2()
        {
            InitializeComponent();
            ComboBoxSetUp(); // Data binds list of objects to the combobox GUI control
        }

        // User clicked Start Game
        private void buttonStart_Click(object sender, EventArgs e)
        {
            // Get user names
            Username1 = textBoxUser1.Text;
            Username2 = textBoxUser2.Text;

            // Get user team colors
            ColorSelect();

            // Get user start resource amount
            StartingResources = (int)comboBoxResources.SelectedValue;

            // Check for valid name and valid team color
            CheckNamesAndColors();

            // Close window
            if (validName && validColor)
            {
                this.DialogResult = DialogResult.OK;
                this.Close();
            }
        }

        // Check for valid name and valid team color
        private void CheckNamesAndColors()
        {
            // Make sure they don't match and make sure neither are blank
            if (Username1 != Username2 && Username1 != "" && Username2 != "")
            {
                validName = true;
                labelInvalidName.Visible = false;
            }
            else
            { 
                validName = false;
                labelInvalidName.Visible = true;
            }

            if (player1color != player2color)
            {
                validColor = true;
                labelInvalidColor.Visible = false;
            }
            else
            {
                validColor = false;
                labelInvalidColor.Visible = true;
            }
        }

        // Sets up the combobox list on the GUI
        private void ComboBoxSetUp()
        {
            // Build a list of ResourceComboBox objects 
            var resourceList = new List<ResourceComboBox>();
            resourceList.Add(new ResourceComboBox() { Name = "$2,500", Value = 2500 });
            resourceList.Add(new ResourceComboBox() { Name = "$7,500", Value = 7500 });
            resourceList.Add(new ResourceComboBox() { Name = "$30,000", Value = 30000 });

            // Set up data binding
            this.comboBoxResources.DataSource = resourceList;
            this.comboBoxResources.DisplayMember = "Name";
            this.comboBoxResources.ValueMember = "Value";
        }

        // Match radio button selected to correct color for user's team color
        private void ColorSelect()
        {
            // LINQ code from StackOverflow.com -- finds which checkbox is checked in groupBox1
            var checkedButton1 = groupBox1.Controls.OfType<RadioButton>()
                                      .FirstOrDefault(r => r.Checked);
            string user1choice = checkedButton1.Text;

            // LINQ code from StackOverflow.com -- finds which checkbox is checked in groupBox2
            var checkedButton2 = groupBox2.Controls.OfType<RadioButton>()
                                      .FirstOrDefault(r => r.Checked);
            string user2choice = checkedButton2.Text;

            // Use the returned string from the button name to set the desired color
            player1color = Color.FromName(user1choice);
            player2color = Color.FromName(user2choice);
        }

        // --- Useless autogenerated label event -- remove if possible! ---
        private void label2_Click(object sender, EventArgs e)
        {

        }
    }

    // Small class for storing combobox list items
    public class ResourceComboBox
    {
        public string Name { get; set; }
        public int Value { get; set; }
    }
}
